version: 0.0.1
title: Lukas Strobel - PhD Researcher
email: lukas.strobel@kit.edu
description: > # this means to ignore newlines until "baseurl:"
  Lukas Strobel is a researcher at the Institute for Anthropomatics and Robotics at the Karlsruhe Institute of Technology (KIT). 
  He holds a Master's degree in Computer Science from Saarland University. 
  His research focuses on Human-Computer Interaction, accessibility and sport.
url: https://lukas-strobel.github.io
timezone: Europe/Berlin
base_url: "/docs"
site_branch: master
github_username:  lukas-strobel
highlighter: rouge
gist:
  noscript: false
exclude:
- readme.md
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  style: compressed
  
